/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsBestPracticesRouteImport } from './routes/docs/best-practices'
import { Route as DocsConfigurationRouteImport } from './routes/docs/configuration'
import { Route as DocsSecurityRouteImport } from './routes/docs/security'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsBestPracticesRoute = DocsBestPracticesRouteImport.update({
  id: '/best-practices',
  path: '/best-practices',
  getParentRoute: () => DocsRoute,
} as any)
const DocsConfigurationRoute = DocsConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSecurityRoute = DocsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/best-practices': typeof DocsBestPracticesRoute
  '/docs/configuration': typeof DocsConfigurationRoute
  '/docs/security': typeof DocsSecurityRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/best-practices': typeof DocsBestPracticesRoute
  '/docs/configuration': typeof DocsConfigurationRoute
  '/docs/security': typeof DocsSecurityRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/best-practices': typeof DocsBestPracticesRoute
  '/docs/configuration': typeof DocsConfigurationRoute
  '/docs/security': typeof DocsSecurityRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/docs' | '/docs/best-practices' | '/docs/configuration' | '/docs/security' | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/docs/best-practices' | '/docs/configuration' | '/docs/security' | '/docs'
  id: '__root__' | '/' | '/docs' | '/docs/best-practices' | '/docs/configuration' | '/docs/security' | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/best-practices': {
      id: '/docs/best-practices'
      path: '/best-practices'
      fullPath: '/docs/best-practices'
      preLoaderRoute: typeof DocsBestPracticesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/configuration': {
      id: '/docs/configuration'
      path: '/configuration'
      fullPath: '/docs/configuration'
      preLoaderRoute: typeof DocsConfigurationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/security': {
      id: '/docs/security'
      path: '/security'
      fullPath: '/docs/security'
      preLoaderRoute: typeof DocsSecurityRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsBestPracticesRoute: typeof DocsBestPracticesRoute
  DocsConfigurationRoute: typeof DocsConfigurationRoute
  DocsSecurityRoute: typeof DocsSecurityRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsBestPracticesRoute: DocsBestPracticesRoute,
  DocsConfigurationRoute: DocsConfigurationRoute,
  DocsSecurityRoute: DocsSecurityRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
